// modules/shared/mockData/dogs.mock.ts
// 30 perros mock — imágenes en /public/assets/dogs/
// Cada raza usa la misma imagen base (dog1–dog8)

import type {
  Dog,
  DogListItem,
  PersonalityTag,
  Vaccination,
} from "../domain/Dog";
import { calcularEdadCategoria } from "../domain/Dog";

// ─── Rutas de imágenes por raza ───────────────────────────────────────────────

const IMGS = {
  labrador: ["/assets/dogs/dog1.jpg"],
  beagle: ["/assets/dogs/dog2.jpg"],
  husky: ["/assets/dogs/dog3.jpg"],
  mestizo: ["/assets/dogs/dog4.jpg"],
  pitbull: ["/assets/dogs/dog5.jpg"],
  golden: ["/assets/dogs/dog6.jpg"],
  salchicha: ["/assets/dogs/dog7.jpg"],
  bulldog: ["/assets/dogs/dog8.jpg"],
};

// ─── Logos de refugios ────────────────────────────────────────────────────────

const SHELTER_LOGOS: Record<string, string> = {
  "huellitas-mx": "/assets/shelters/shelter1-logo.jpg",
  "patitas-libres": "/assets/shelters/shelter2-logo.jpg",
  "amigos-4-patas": "/assets/shelters/shelter3-logo.jpg",
  "refugio-esperanza": "/assets/shelters/shelter4-logo.jpg",
  "segunda-oportunidad": "/assets/shelters/shelter5-logo.jpg",
};

// ─── Tags de personalidad reutilizables ──────────────────────────────────────

// icon = nombre de Material Symbol (se renderiza con <DogAttributeIcon iconName={tag.icon} />)
const TAGS: Record<string, PersonalityTag> = {
  jugueton: {
    id: "1",
    label: "Juguetón",
    icon: "sports_tennis",
    categoria: "caracter",
  },
  tranquilo: {
    id: "2",
    label: "Tranquilo",
    icon: "self_care",
    categoria: "caracter",
  },
  protector: {
    id: "3",
    label: "Protector",
    icon: "security",
    categoria: "caracter",
  },
  curioso: { id: "4", label: "Curioso", icon: "search", categoria: "caracter" },
  leal: { id: "5", label: "Leal", icon: "favorite", categoria: "caracter" },
  energico: { id: "6", label: "Enérgico", icon: "bolt", categoria: "actividad" },
  relajado: {
    id: "7",
    label: "Relajado",
    icon: "weekend",
    categoria: "actividad",
  },
  sociable: {
    id: "8",
    label: "Sociable",
    icon: "pets",
    categoria: "socializacion",
  },
  timido: { id: "9", label: "Tímido", icon: "hide", categoria: "socializacion" },
  independiente: {
    id: "10",
    label: "Independiente",
    icon: "flight",
    categoria: "caracter",
  },
  obediente: {
    id: "11",
    label: "Obediente",
    icon: "check_circle",
    categoria: "entrenamiento",
  },
  terco: {
    id: "12",
    label: "Terco",
    icon: "sentiment_neutral",
    categoria: "entrenamiento",
  },
  cariñoso: {
    id: "13",
    label: "Cariñoso",
    icon: "volunteer_activism",
    categoria: "caracter",
  },
  activo: {
    id: "14",
    label: "Activo",
    icon: "directions_run",
    categoria: "actividad",
  },
  cazador: {
    id: "15",
    label: "Instinto cazador",
    icon: "track_changes",
    categoria: "caracter",
  },
};

// ─── Vacunas reutilizables ────────────────────────────────────────────────────

const VAC_COMPLETAS: Vaccination[] = [
  {
    id: "1",
    nombre: "Rabia",
    fecha: "2024-03-15",
    proximaDosis: "2025-03-15",
    verificada: true,
  },
  {
    id: "2",
    nombre: "Parvovirus",
    fecha: "2024-03-15",
    proximaDosis: "2025-03-15",
    verificada: true,
  },
  {
    id: "3",
    nombre: "Distemper",
    fecha: "2024-03-15",
    proximaDosis: "2025-03-15",
    verificada: true,
  },
  {
    id: "4",
    nombre: "Leptospirosis",
    fecha: "2024-06-01",
    proximaDosis: "2025-06-01",
    verificada: true,
  },
];

const VAC_INCOMPLETAS: Vaccination[] = [
  {
    id: "1",
    nombre: "Rabia",
    fecha: "2024-03-15",
    proximaDosis: "2025-03-15",
    verificada: true,
  },
  { id: "2", nombre: "Parvovirus", fecha: "2024-03-15", verificada: false },
];

const VAC_BASICAS: Vaccination[] = [
  {
    id: "1",
    nombre: "Rabia",
    fecha: "2024-08-10",
    proximaDosis: "2025-08-10",
    verificada: true,
  },
  { id: "2", nombre: "Parvovirus", fecha: "2024-08-10", verificada: true },
];

// ─── 30 Perros mock ──────────────────────────────────────────────────────────

export const MOCK_DOGS: Dog[] = [
  // ── REFUGIO 1 — Huellitas MX (shelter-001) ──────────────────────────────

  {
    id: "1",
    userOwnerId: "owner-1",
    refugioId: "1",
    nombre: "Max",
    raza: "Labrador",
    edad: 24,
    pesoKg: 28,
    sexo: "macho",
    tamano: "grande",
    nivelEnergia: "alta",
    descripcion:
      "Max es un Labrador cariñoso y lleno de energía. Le encanta correr y jugar con niños. Busca una familia activa con jardín.",
    estado: "disponible",
    personalidad: [TAGS.jugueton, TAGS.energico, TAGS.sociable, TAGS.cariñoso],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: false,
    castrado: true,
    necesitaJardin: true,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "corto",
    vacunas: VAC_COMPLETAS,
    salud: "Vacunado, desparasitado",
    foto: IMGS.labrador[0],
    fotos: IMGS.labrador,
    edadCategoria: calcularEdadCategoria(24),
    compatibilidad: 0,
    refugioNombre: "Huellitas MX",
    refugioLogo: SHELTER_LOGOS["huellitas-mx"],
    fechaRegistro: "2024-10-01",
  },
  {
    id: "2",
    userOwnerId: "owner-1",
    refugioId: "1",
    nombre: "Luna",
    raza: "Beagle",
    edad: 8,
    pesoKg: 9,
    sexo: "hembra",
    tamano: "mediano",
    nivelEnergia: "moderada",
    descripcion:
      "Luna es una cachorra curiosa y juguetona. Se lleva bien con todos. Ideal para apartamento si se le hace ejercicio diario.",
    estado: "disponible",
    personalidad: [TAGS.curioso, TAGS.jugueton, TAGS.sociable],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: true,
    castrado: false,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "corto",
    vacunas: VAC_BASICAS,
    salud: "Vacunada, desparasitada",
    foto: IMGS.beagle[0],
    fotos: IMGS.beagle,
    edadCategoria: calcularEdadCategoria(8),
    compatibilidad: 0,
    refugioNombre: "Huellitas MX",
    refugioLogo: SHELTER_LOGOS["huellitas-mx"],
    fechaRegistro: "2024-11-15",
  },
  {
    id: "3",
    userOwnerId: "owner-1",
    refugioId: "1",
    nombre: "Thor",
    raza: "Husky Siberiano",
    edad: 36,
    pesoKg: 25,
    sexo: "macho",
    tamano: "grande",
    nivelEnergia: "muy_alta",
    descripcion:
      "Thor es un Husky impresionante, lleno de vida. Necesita mucho ejercicio diario y espacio. No apto para primeros dueños sin experiencia.",
    estado: "disponible",
    personalidad: [TAGS.energico, TAGS.independiente, TAGS.curioso, TAGS.terco],
    aptoNinos: false,
    aptoPerros: true,
    aptoGatos: false,
    castrado: true,
    necesitaJardin: true,
    estaVacunado: true,
    estaDesparasitado: false,
    largoPelaje: "largo",
    vacunas: VAC_INCOMPLETAS,
    salud: "Vacunado, necesita refuerzo de leptospirosis",
    foto: IMGS.husky[0],
    fotos: IMGS.husky,
    edadCategoria: calcularEdadCategoria(36),
    compatibilidad: 0,
    refugioNombre: "Huellitas MX",
    refugioLogo: SHELTER_LOGOS["huellitas-mx"],
    fechaRegistro: "2024-09-20",
  },
  {
    id: "4",
    userOwnerId: "owner-1",
    refugioId: "1",
    nombre: "Coco",
    raza: "Mestizo",
    edad: 60,
    pesoKg: 7,
    sexo: "hembra",
    tamano: "pequeño",
    nivelEnergia: "baja",
    descripcion:
      "Coco es una perrita adulta tranquila y leal. Perfecta para departamento. Lleva 2 años en el refugio esperando un hogar.",
    estado: "disponible",
    personalidad: [TAGS.tranquilo, TAGS.leal, TAGS.cariñoso],
    aptoNinos: true,
    aptoPerros: false,
    aptoGatos: true,
    castrado: true,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "corto",
    vacunas: VAC_COMPLETAS,
    salud: "Vacunada, desparasitada, esterilizada",
    foto: IMGS.mestizo[0],
    fotos: IMGS.mestizo,
    edadCategoria: calcularEdadCategoria(60),
    compatibilidad: 0,
    refugioNombre: "Huellitas MX",
    refugioLogo: SHELTER_LOGOS["huellitas-mx"],
    fechaRegistro: "2023-06-10",
  },
  {
    id: "5",
    userOwnerId: "owner-1",
    refugioId: "1",
    nombre: "Rocky",
    raza: "Pitbull",
    edad: 18,
    pesoKg: 20,
    sexo: "macho",
    tamano: "mediano",
    nivelEnergia: "alta",
    descripcion:
      "Rocky es un Pitbull muy sociable y cariñoso. Desmiente todos los mitos de su raza. Necesita dueño con experiencia.",
    estado: "en_proceso",
    personalidad: [TAGS.sociable, TAGS.energico, TAGS.leal, TAGS.jugueton],
    aptoNinos: true,
    aptoPerros: false,
    aptoGatos: false,
    castrado: true,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "corto",
    vacunas: VAC_COMPLETAS,
    salud: "Vacunado, desparasitado",
    foto: IMGS.pitbull[0],
    fotos: IMGS.pitbull,
    edadCategoria: calcularEdadCategoria(18),
    compatibilidad: 0,
    refugioNombre: "Huellitas MX",
    refugioLogo: SHELTER_LOGOS["huellitas-mx"],
    fechaRegistro: "2024-08-05",
  },
  {
    id: "6",
    userOwnerId: "owner-1",
    refugioId: "1",
    nombre: "Bella",
    raza: "Golden Retriever",
    edad: 48,
    pesoKg: 26,
    sexo: "hembra",
    tamano: "grande",
    nivelEnergia: "moderada",
    descripcion: "Bella fue adoptada en enero. Una historia de éxito.",
    estado: "adoptado",
    personalidad: [TAGS.cariñoso, TAGS.obediente, TAGS.sociable],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: true,
    castrado: true,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "largo",
    vacunas: VAC_COMPLETAS,
    salud: "Vacunada, desparasitada",
    foto: IMGS.golden[0],
    fotos: IMGS.golden,
    edadCategoria: calcularEdadCategoria(48),
    compatibilidad: 0,
    refugioNombre: "Huellitas MX",
    refugioLogo: SHELTER_LOGOS["huellitas-mx"],
    fechaRegistro: "2024-01-15",
  },

  // ── REFUGIO 2 — Patitas Libres (shelter-002) ─────────────────────────────

  {
    id: "7",
    userOwnerId: "owner-2",
    refugioId: "2",
    nombre: "Churro",
    raza: "Salchicha",
    edad: 6,
    pesoKg: 4,
    sexo: "macho",
    tamano: "pequeño",
    nivelEnergia: "moderada",
    descripcion:
      "Churro es un cachorro Salchicha adorable. Pequeño, curioso y muy apegado a las personas. Ideal para departamento.",
    estado: "disponible",
    personalidad: [TAGS.curioso, TAGS.cariñoso, TAGS.jugueton],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: true,
    castrado: false,
    necesitaJardin: false,
    estaVacunado: false,
    estaDesparasitado: false,
    largoPelaje: "corto",
    vacunas: VAC_INCOMPLETAS,
    salud: "Primera vacuna aplicada, pendiente refuerzo",
    foto: IMGS.salchicha[0],
    fotos: IMGS.salchicha,
    edadCategoria: calcularEdadCategoria(6),
    compatibilidad: 0,
    refugioNombre: "Patitas Libres",
    refugioLogo: SHELTER_LOGOS["patitas-libres"],
    fechaRegistro: "2024-12-01",
  },
  {
    id: "8",
    userOwnerId: "owner-2",
    refugioId: "2",
    nombre: "Nala",
    raza: "Bulldog Francés",
    edad: 30,
    pesoKg: 10,
    sexo: "hembra",
    tamano: "pequeño",
    nivelEnergia: "baja",
    descripcion:
      "Nala tiene un soplo leve pero lleva vida normal. Tranquila, perfecta para personas mayores o que trabajan desde casa.",
    estado: "disponible",
    personalidad: [TAGS.tranquilo, TAGS.relajado, TAGS.cariñoso],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: true,
    castrado: true,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "corto",
    vacunas: VAC_COMPLETAS,
    salud: "Vacunada, desparasitada, problema respiratorio leve",
    foto: IMGS.bulldog[0],
    fotos: IMGS.bulldog,
    edadCategoria: calcularEdadCategoria(30),
    compatibilidad: 0,
    refugioNombre: "Patitas Libres",
    refugioLogo: SHELTER_LOGOS["patitas-libres"],
    fechaRegistro: "2024-07-20",
  },
  {
    id: "9",
    userOwnerId: "owner-2",
    refugioId: "2",
    nombre: "Lobo",
    raza: "Mestizo",
    edad: 84,
    pesoKg: 30,
    sexo: "macho",
    tamano: "grande",
    nivelEnergia: "baja",
    descripcion:
      "Lobo es un perro senior tranquilo. Su artritis no le impide dar paseos cortos. Merece pasar sus últimos años en familia.",
    estado: "disponible",
    personalidad: [TAGS.tranquilo, TAGS.leal, TAGS.relajado],
    aptoNinos: false,
    aptoPerros: true,
    aptoGatos: false,
    castrado: true,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: false,
    largoPelaje: "mediano",
    vacunas: VAC_BASICAS,
    salud: "Vacunado, artritis leve en patas traseras",
    foto: IMGS.mestizo[0],
    fotos: IMGS.mestizo,
    edadCategoria: calcularEdadCategoria(84),
    compatibilidad: 0,
    refugioNombre: "Patitas Libres",
    refugioLogo: SHELTER_LOGOS["patitas-libres"],
    fechaRegistro: "2023-03-05",
  },
  {
    id: "10",
    userOwnerId: "owner-2",
    refugioId: "2",
    nombre: "Mia",
    raza: "Beagle",
    edad: 12,
    pesoKg: 11,
    sexo: "hembra",
    tamano: "mediano",
    nivelEnergia: "moderada",
    descripcion:
      "Mia es una Beagle joven y equilibrada. Sigue muy bien órdenes básicas. Ideal para familia con niños.",
    estado: "disponible",
    personalidad: [TAGS.obediente, TAGS.sociable, TAGS.cariñoso],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: true,
    castrado: false,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "corto",
    vacunas: VAC_COMPLETAS,
    salud: "Vacunada, desparasitada",
    foto: IMGS.beagle[0],
    fotos: IMGS.beagle,
    edadCategoria: calcularEdadCategoria(12),
    compatibilidad: 0,
    refugioNombre: "Patitas Libres",
    refugioLogo: SHELTER_LOGOS["patitas-libres"],
    fechaRegistro: "2024-10-30",
  },
  {
    id: "11",
    userOwnerId: "owner-2",
    refugioId: "2",
    nombre: "Simba",
    raza: "Labrador",
    edad: 15,
    pesoKg: 22,
    sexo: "macho",
    tamano: "grande",
    nivelEnergia: "alta",
    descripcion:
      "Simba es un Labrador amarillo juvenil, muy activo. Ya tiene solicitud en revisión.",
    estado: "en_proceso",
    personalidad: [TAGS.energico, TAGS.jugueton, TAGS.sociable],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: false,
    castrado: false,
    necesitaJardin: true,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "corto",
    vacunas: VAC_BASICAS,
    salud: "Vacunado, desparasitado",
    foto: IMGS.labrador[0],
    fotos: IMGS.labrador,
    edadCategoria: calcularEdadCategoria(15),
    compatibilidad: 0,
    refugioNombre: "Patitas Libres",
    refugioLogo: SHELTER_LOGOS["patitas-libres"],
    fechaRegistro: "2024-11-01",
  },
  {
    id: "12",
    userOwnerId: "owner-2",
    refugioId: "2",
    nombre: "Canela",
    raza: "Golden Retriever",
    edad: 96,
    pesoKg: 27,
    sexo: "hembra",
    tamano: "grande",
    nivelEnergia: "baja",
    descripcion:
      "Canela es una Golden senior dulcísima. Su hipotiroidismo está 100% controlado. Pide una casita tranquila para descansar.",
    estado: "disponible",
    personalidad: [TAGS.tranquilo, TAGS.cariñoso, TAGS.leal],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: true,
    castrado: true,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "largo",
    vacunas: VAC_COMPLETAS,
    salud: "Vacunada, hipotiroidismo controlado con medicación",
    foto: IMGS.golden[0],
    fotos: IMGS.golden,
    edadCategoria: calcularEdadCategoria(96),
    compatibilidad: 0,
    refugioNombre: "Patitas Libres",
    refugioLogo: SHELTER_LOGOS["patitas-libres"],
    fechaRegistro: "2023-08-12",
  },

  // ── REFUGIO 3 — Amigos de 4 Patas (shelter-003) ──────────────────────────

  {
    id: "13",
    userOwnerId: "owner-3",
    refugioId: "3",
    nombre: "Dante",
    raza: "Pitbull",
    edad: 20,
    pesoKg: 19,
    sexo: "macho",
    tamano: "mediano",
    nivelEnergia: "alta",
    descripcion:
      "Dante llegó de una situación de abandono. Ha recuperado la confianza con paciencia. Necesita dueño tranquilo y firme.",
    estado: "disponible",
    personalidad: [TAGS.timido, TAGS.leal, TAGS.cariñoso],
    aptoNinos: false,
    aptoPerros: false,
    aptoGatos: false,
    castrado: true,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "corto",
    vacunas: VAC_COMPLETAS,
    salud: "Vacunado, desparasitado",
    foto: IMGS.pitbull[0],
    fotos: IMGS.pitbull,
    edadCategoria: calcularEdadCategoria(20),
    compatibilidad: 0,
    refugioNombre: "Amigos de 4 Patas",
    refugioLogo: SHELTER_LOGOS["amigos-4-patas"],
    fechaRegistro: "2024-06-18",
  },
  {
    id: "14",
    userOwnerId: "owner-3",
    refugioId: "3",
    nombre: "Fiona",
    raza: "Husky Siberiano",
    edad: 10,
    pesoKg: 22,
    sexo: "hembra",
    tamano: "grande",
    nivelEnergia: "muy_alta",
    descripcion:
      "Fiona es una Husky joven con muchísima energía. Necesita ejercicio intenso diario. Hará a alguien muy feliz si puede seguirle el ritmo.",
    estado: "disponible",
    personalidad: [
      TAGS.energico,
      TAGS.curioso,
      TAGS.activo,
      TAGS.independiente,
    ],
    aptoNinos: false,
    aptoPerros: true,
    aptoGatos: false,
    castrado: false,
    necesitaJardin: true,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "largo",
    vacunas: VAC_BASICAS,
    salud: "Vacunada, desparasitada",
    foto: IMGS.husky[0],
    fotos: IMGS.husky,
    edadCategoria: calcularEdadCategoria(10),
    compatibilidad: 0,
    refugioNombre: "Amigos de 4 Patas",
    refugioLogo: SHELTER_LOGOS["amigos-4-patas"],
    fechaRegistro: "2024-09-05",
  },
  {
    id: "15",
    userOwnerId: "owner-3",
    refugioId: "3",
    nombre: "Pepito",
    raza: "Salchicha",
    edad: 5,
    pesoKg: 3,
    sexo: "macho",
    tamano: "pequeño",
    nivelEnergia: "moderada",
    descripcion:
      "Pepito es un cachorro pequeñísimo con mucha personalidad. Muy vocal y expresivo. Se adapta bien a espacios pequeños.",
    estado: "disponible",
    personalidad: [TAGS.curioso, TAGS.terco, TAGS.jugueton],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: false,
    castrado: false,
    necesitaJardin: false,
    estaVacunado: false,
    estaDesparasitado: false,
    largoPelaje: "corto",
    vacunas: VAC_INCOMPLETAS,
    salud: "Primera vacuna aplicada",
    foto: IMGS.salchicha[0],
    fotos: IMGS.salchicha,
    edadCategoria: calcularEdadCategoria(5),
    compatibilidad: 0,
    refugioNombre: "Amigos de 4 Patas",
    refugioLogo: SHELTER_LOGOS["amigos-4-patas"],
    fechaRegistro: "2024-12-10",
  },
  {
    id: "16",
    userOwnerId: "owner-3",
    refugioId: "3",
    nombre: "Princesa",
    raza: "Bulldog Francés",
    edad: 42,
    pesoKg: 12,
    sexo: "hembra",
    tamano: "pequeño",
    nivelEnergia: "baja",
    descripcion:
      "Princesa es una Bulldog adulta muy tranquila. Ama los sofás y los mimos. Perfecta para personas que buscan compañía sin mucha actividad.",
    estado: "disponible",
    personalidad: [TAGS.relajado, TAGS.cariñoso, TAGS.tranquilo],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: true,
    castrado: true,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "corto",
    vacunas: VAC_COMPLETAS,
    salud: "Vacunada, esterilizada",
    foto: IMGS.bulldog[0],
    fotos: IMGS.bulldog,
    edadCategoria: calcularEdadCategoria(42),
    compatibilidad: 0,
    refugioNombre: "Amigos de 4 Patas",
    refugioLogo: SHELTER_LOGOS["amigos-4-patas"],
    fechaRegistro: "2024-05-20",
  },
  {
    id: "17",
    userOwnerId: "owner-3",
    refugioId: "3",
    nombre: "Bruno",
    raza: "Labrador",
    edad: 55,
    pesoKg: 30,
    sexo: "macho",
    tamano: "grande",
    nivelEnergia: "moderada",
    descripcion: "Bruno fue adoptado por una familia de la CDMX.",
    estado: "adoptado",
    personalidad: [TAGS.leal, TAGS.obediente, TAGS.sociable],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: true,
    castrado: true,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "corto",
    vacunas: VAC_COMPLETAS,
    salud: "Vacunado, desparasitado",
    foto: IMGS.labrador[0],
    fotos: IMGS.labrador,
    edadCategoria: calcularEdadCategoria(55),
    compatibilidad: 0,
    refugioNombre: "Amigos de 4 Patas",
    refugioLogo: SHELTER_LOGOS["amigos-4-patas"],
    fechaRegistro: "2023-11-10",
  },

  // ── REFUGIO 4 — Refugio Esperanza (shelter-004) ───────────────────────────

  {
    id: "18",
    userOwnerId: "owner-4",
    refugioId: "4",
    nombre: "Kira",
    raza: "Mestizo",
    edad: 14,
    pesoKg: 14,
    sexo: "hembra",
    tamano: "mediano",
    nivelEnergia: "moderada",
    descripcion:
      "Kira es una mestiza equilibrada y cariñosa. Se adapta a casi cualquier hogar. Muy buena con niños mayores.",
    estado: "disponible",
    personalidad: [TAGS.cariñoso, TAGS.sociable, TAGS.obediente],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: true,
    castrado: false,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "mediano",
    vacunas: VAC_BASICAS,
    salud: "Vacunada, desparasitada",
    foto: IMGS.mestizo[0],
    fotos: IMGS.mestizo,
    edadCategoria: calcularEdadCategoria(14),
    compatibilidad: 0,
    refugioNombre: "Refugio Esperanza",
    refugioLogo: SHELTER_LOGOS["refugio-esperanza"],
    fechaRegistro: "2024-10-15",
  },
  {
    id: "19",
    userOwnerId: "owner-4",
    refugioId: "4",
    nombre: "Oreo",
    raza: "Bulldog Francés",
    edad: 3,
    pesoKg: 2,
    sexo: "macho",
    tamano: "pequeño",
    nivelEnergia: "moderada",
    descripcion:
      "Oreo llegó hace poco, aún muy bebé. Blanco y negro como su nombre. Tierno y dormilón.",
    estado: "disponible",
    personalidad: [TAGS.curioso, TAGS.jugueton],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: true,
    castrado: false,
    necesitaJardin: false,
    estaVacunado: false,
    estaDesparasitado: false,
    largoPelaje: "corto",
    vacunas: VAC_INCOMPLETAS,
    salud: "Primera vacuna esta semana",
    foto: IMGS.bulldog[0],
    fotos: IMGS.bulldog,
    edadCategoria: calcularEdadCategoria(3),
    compatibilidad: 0,
    refugioNombre: "Refugio Esperanza",
    refugioLogo: SHELTER_LOGOS["refugio-esperanza"],
    fechaRegistro: "2025-01-02",
  },
  {
    id: "20",
    userOwnerId: "owner-4",
    refugioId: "4",
    nombre: "Sasha",
    raza: "Husky Siberiano",
    edad: 72,
    pesoKg: 24,
    sexo: "hembra",
    tamano: "grande",
    nivelEnergia: "moderada",
    descripcion:
      "Sasha ya no tiene la energía de antes. Una Husky adulta que prefiere caminatas tranquilas. Impresionante y noble.",
    estado: "disponible",
    personalidad: [TAGS.tranquilo, TAGS.independiente, TAGS.leal],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: false,
    castrado: true,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "largo",
    vacunas: VAC_COMPLETAS,
    salud: "Vacunada, esterilizada",
    foto: IMGS.husky[0],
    fotos: IMGS.husky,
    edadCategoria: calcularEdadCategoria(72),
    compatibilidad: 0,
    refugioNombre: "Refugio Esperanza",
    refugioLogo: SHELTER_LOGOS["refugio-esperanza"],
    fechaRegistro: "2024-04-22",
  },
  {
    id: "21",
    userOwnerId: "owner-4",
    refugioId: "4",
    nombre: "Rex",
    raza: "Pitbull",
    edad: 18,
    pesoKg: 21,
    sexo: "macho",
    tamano: "mediano",
    nivelEnergia: "alta",
    descripcion: "Rex está en proceso de adopción con una familia de Tlalpan.",
    estado: "en_proceso",
    personalidad: [TAGS.protector, TAGS.leal, TAGS.energico],
    aptoNinos: false,
    aptoPerros: false,
    aptoGatos: false,
    castrado: true,
    necesitaJardin: true,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "corto",
    vacunas: VAC_COMPLETAS,
    salud: "Vacunado, desparasitado",
    foto: IMGS.pitbull[0],
    fotos: IMGS.pitbull,
    edadCategoria: calcularEdadCategoria(18),
    compatibilidad: 0,
    refugioNombre: "Refugio Esperanza",
    refugioLogo: SHELTER_LOGOS["refugio-esperanza"],
    fechaRegistro: "2024-08-30",
  },
  {
    id: "22",
    userOwnerId: "owner-4",
    refugioId: "4",
    nombre: "Gala",
    raza: "Golden Retriever",
    edad: 36,
    pesoKg: 25,
    sexo: "hembra",
    tamano: "grande",
    nivelEnergia: "moderada",
    descripcion:
      "Gala es una Golden clásica: dulce, gentil y paciente. Excelente con niños de cualquier edad.",
    estado: "disponible",
    personalidad: [TAGS.cariñoso, TAGS.obediente, TAGS.sociable, TAGS.leal],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: true,
    castrado: true,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "largo",
    vacunas: VAC_COMPLETAS,
    salud: "Vacunada, desparasitada",
    foto: IMGS.golden[0],
    fotos: IMGS.golden,
    edadCategoria: calcularEdadCategoria(36),
    compatibilidad: 0,
    refugioNombre: "Refugio Esperanza",
    refugioLogo: SHELTER_LOGOS["refugio-esperanza"],
    fechaRegistro: "2024-07-10",
  },

  // ── REFUGIO 5 — Segunda Oportunidad (shelter-005) ────────────────────────

  {
    id: "23",
    userOwnerId: "owner-5",
    refugioId: "5",
    nombre: "Toby",
    raza: "Beagle",
    edad: 48,
    pesoKg: 12,
    sexo: "macho",
    tamano: "mediano",
    nivelEnergia: "moderada",
    descripcion:
      "Toby tiene 4 años y sigue tan curioso como el primer día. Olfato increíble. Le encanta explorar parques.",
    estado: "disponible",
    personalidad: [TAGS.curioso, TAGS.activo, TAGS.cazador, TAGS.sociable],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: false,
    castrado: true,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "corto",
    vacunas: VAC_COMPLETAS,
    salud: "Vacunado, desparasitado",
    foto: IMGS.beagle[0],
    fotos: IMGS.beagle,
    edadCategoria: calcularEdadCategoria(48),
    compatibilidad: 0,
    refugioNombre: "Segunda Oportunidad",
    refugioLogo: SHELTER_LOGOS["segunda-oportunidad"],
    fechaRegistro: "2024-09-12",
  },
  {
    id: "24",
    userOwnerId: "owner-5",
    refugioId: "5",
    nombre: "Nina",
    raza: "Mestizo",
    edad: 7,
    pesoKg: 5,
    sexo: "hembra",
    tamano: "pequeño",
    nivelEnergia: "moderada",
    descripcion:
      "Nina es una cachorrota mestiza diminuta. Muy lista, aprende trucos rápido. Primera vacuna hace 2 semanas.",
    estado: "disponible",
    personalidad: [TAGS.curioso, TAGS.jugueton, TAGS.sociable],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: true,
    castrado: false,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: false,
    largoPelaje: "corto",
    vacunas: VAC_INCOMPLETAS,
    salud: "Vacunada, primera dosis",
    foto: IMGS.mestizo[0],
    fotos: IMGS.mestizo,
    edadCategoria: calcularEdadCategoria(7),
    compatibilidad: 0,
    refugioNombre: "Segunda Oportunidad",
    refugioLogo: SHELTER_LOGOS["segunda-oportunidad"],
    fechaRegistro: "2024-12-20",
  },
  {
    id: "25",
    userOwnerId: "owner-5",
    refugioId: "5",
    nombre: "Duke",
    raza: "Labrador",
    edad: 60,
    pesoKg: 29,
    sexo: "macho",
    tamano: "grande",
    nivelEnergia: "moderada",
    descripcion:
      "Duke tiene displasia leve controlada. Camina bien con tratamiento mensual. Necesita familia comprometida y paciente.",
    estado: "disponible",
    personalidad: [TAGS.tranquilo, TAGS.leal, TAGS.obediente],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: true,
    castrado: true,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "corto",
    vacunas: VAC_COMPLETAS,
    salud: "Vacunado, displasia leve en cadera",
    foto: IMGS.labrador[0],
    fotos: IMGS.labrador,
    edadCategoria: calcularEdadCategoria(60),
    compatibilidad: 0,
    refugioNombre: "Segunda Oportunidad",
    refugioLogo: SHELTER_LOGOS["segunda-oportunidad"],
    fechaRegistro: "2023-09-01",
  },
  {
    id: "26",
    userOwnerId: "owner-5",
    refugioId: "5",
    nombre: "Panda",
    raza: "Bulldog Francés",
    edad: 22,
    pesoKg: 11,
    sexo: "macho",
    tamano: "pequeño",
    nivelEnergia: "baja",
    descripcion:
      "Panda es blanco y negro, rechoncho y adorable. Le gustan las siestas largas y los abrazos. Bajo mantenimiento.",
    estado: "disponible",
    personalidad: [TAGS.relajado, TAGS.cariñoso, TAGS.tranquilo],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: true,
    castrado: false,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "corto",
    vacunas: VAC_BASICAS,
    salud: "Vacunado, desparasitado",
    foto: IMGS.bulldog[0],
    fotos: IMGS.bulldog,
    edadCategoria: calcularEdadCategoria(22),
    compatibilidad: 0,
    refugioNombre: "Segunda Oportunidad",
    refugioLogo: SHELTER_LOGOS["segunda-oportunidad"],
    fechaRegistro: "2024-11-08",
  },
  {
    id: "27",
    userOwnerId: "owner-5",
    refugioId: "5",
    nombre: "Alaska",
    raza: "Husky Siberiano",
    edad: 16,
    pesoKg: 20,
    sexo: "hembra",
    tamano: "grande",
    nivelEnergia: "muy_alta",
    descripcion:
      "Alaska es una Husky jovencísima, pura energía. Ojos celestes hipnóticos. Solo para gente muy activa con experiencia en la raza.",
    estado: "disponible",
    personalidad: [
      TAGS.energico,
      TAGS.curioso,
      TAGS.independiente,
      TAGS.activo,
    ],
    aptoNinos: false,
    aptoPerros: true,
    aptoGatos: false,
    castrado: false,
    necesitaJardin: true,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "largo",
    vacunas: VAC_BASICAS,
    salud: "Vacunada, desparasitada",
    foto: IMGS.husky[0],
    fotos: IMGS.husky,
    edadCategoria: calcularEdadCategoria(16),
    compatibilidad: 0,
    refugioNombre: "Segunda Oportunidad",
    refugioLogo: SHELTER_LOGOS["segunda-oportunidad"],
    fechaRegistro: "2024-10-25",
  },
  {
    id: "28",
    userOwnerId: "owner-5",
    refugioId: "5",
    nombre: "Manchas",
    raza: "Mestizo",
    edad: 108,
    pesoKg: 16,
    sexo: "macho",
    tamano: "mediano",
    nivelEnergia: "baja",
    descripcion:
      "Manchas tiene 9 años y sordera parcial. Responde a señas. El más veterano del refugio — lleva 3 años esperando. Merece un hogar.",
    estado: "disponible",
    personalidad: [TAGS.tranquilo, TAGS.leal, TAGS.relajado],
    aptoNinos: false,
    aptoPerros: true,
    aptoGatos: true,
    castrado: true,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "mediano",
    vacunas: VAC_COMPLETAS,
    salud: "Vacunado, sordera parcial",
    foto: IMGS.mestizo[0],
    fotos: IMGS.mestizo,
    edadCategoria: calcularEdadCategoria(108),
    compatibilidad: 0,
    refugioNombre: "Segunda Oportunidad",
    refugioLogo: SHELTER_LOGOS["segunda-oportunidad"],
    fechaRegistro: "2022-04-15",
  },
  {
    id: "29",
    userOwnerId: "owner-5",
    refugioId: "5",
    nombre: "Frida",
    raza: "Salchicha",
    edad: 28,
    pesoKg: 6,
    sexo: "hembra",
    tamano: "pequeño",
    nivelEnergia: "moderada",
    descripcion:
      "Frida tiene solicitud activa. Pequeña pero con carácter. Le fascina cavar.",
    estado: "en_proceso",
    personalidad: [TAGS.curioso, TAGS.terco, TAGS.cariñoso],
    aptoNinos: true,
    aptoPerros: false,
    aptoGatos: true,
    castrado: true,
    necesitaJardin: false,
    estaVacunado: true,
    estaDesparasitado: true,
    largoPelaje: "corto",
    vacunas: VAC_COMPLETAS,
    salud: "Vacunada, esterilizada",
    foto: IMGS.salchicha[0],
    fotos: IMGS.salchicha,
    edadCategoria: calcularEdadCategoria(28),
    compatibilidad: 0,
    refugioNombre: "Segunda Oportunidad",
    refugioLogo: SHELTER_LOGOS["segunda-oportunidad"],
    fechaRegistro: "2024-08-18",
  },
  {
    id: "30",
    userOwnerId: "owner-5",
    refugioId: "5",
    nombre: "Goldie",
    raza: "Golden Retriever",
    edad: 4,
    pesoKg: 8,
    sexo: "hembra",
    tamano: "grande",
    nivelEnergia: "alta",
    descripcion:
      "Goldie es la más nueva del refugio. Cachorra Golden que promete ser la mejor amiga de alguien muy afortunado.",
    estado: "disponible",
    personalidad: [TAGS.jugueton, TAGS.curioso, TAGS.sociable],
    aptoNinos: true,
    aptoPerros: true,
    aptoGatos: true,
    castrado: false,
    necesitaJardin: false,
    estaVacunado: false,
    estaDesparasitado: false,
    largoPelaje: "largo",
    vacunas: VAC_INCOMPLETAS,
    salud: "Primera vacuna aplicada, pendiente esquema completo",
    foto: IMGS.golden[0],
    fotos: IMGS.golden,
    edadCategoria: calcularEdadCategoria(4),
    compatibilidad: 0,
    refugioNombre: "Segunda Oportunidad",
    refugioLogo: SHELTER_LOGOS["segunda-oportunidad"],
    fechaRegistro: "2025-01-10",
  },
];

// ─── Helper functions ─────────────────────────────────────────────────────────

export const getDogById = (id: string): Dog | undefined =>
  MOCK_DOGS.find((d) => d.id === id);

export const getDogBySlug = (slug: string): Dog | undefined =>
  MOCK_DOGS.find((d) => d.nombre.toLowerCase().replace(/\s+/g, "-") === slug);

export const getDogsByShelterId = (refugioId: string): Dog[] =>
  MOCK_DOGS.filter((d) => d.refugioId === refugioId);

export const getAvailableDogs = (): Dog[] =>
  MOCK_DOGS.filter((d) => d.estado === "disponible");

export const getDogListItem = (dog: Dog): DogListItem => ({
  id: dog.id,
  refugioId: dog.refugioId,
  nombre: dog.nombre,
  edad: dog.edad,
  edadCategoria: dog.edadCategoria,
  raza: dog.raza,
  tamano: dog.tamano,
  sexo: dog.sexo,
  nivelEnergia: dog.nivelEnergia,
  estado: dog.estado,
  foto: dog.foto,
  compatibilidad: dog.compatibilidad,
  aptoNinos: dog.aptoNinos,
  aptoPerros: dog.aptoPerros,
  necesitaJardin: dog.necesitaJardin,
  refugioNombre: dog.refugioNombre,
});

export const MOCK_DOGS_LIST: DogListItem[] = MOCK_DOGS.map(getDogListItem);
