export type GetShelterProfileApiResponse = {
  id: string;
  userOwnerId: string;
  name: string;
  description: string | null;
  phone: string | null;
  email: string | null;
  website: string | null;
  municipality: string | null;
  fullAddress: string | null;
  schedule: string | null;
  facebook: string | null;
  instagram: string | null;
  twitter: string | null;
  approved: boolean;
  status: "pending" | "approved" | "rejected" | "suspended";
  logo: string | null;
  imageUrl: string | null;
  adoptionFee: number | null;
  createdAt: Date;
  updatedAt: Date;
};

export type UpdateShelterApiResponse = {
  id: string;
  userOwnerId: string;
  name: string;
  description: string | null;
  phone: string | null;
  email: string | null;
  website: string | null;
  municipality: string | null;
  fullAddress: string | null;
  schedule: string | null;
  facebook: string | null;
  instagram: string | null;
  twitter: string | null;
  approved: boolean;
  status: "pending" | "approved" | "rejected" | "suspended";
  logo: string | null;
  imageUrl: string | null;
  adoptionFee: number | null;
  createdAt: Date;
  updatedAt: Date;
};
