export type GetShelterProfileApiResponse = {
  id: string;
  name: string;
  description: string | null;
  phone: string | null;
  email: string | null;
  website: string | null;
  municipality: string | null;
  fullAddress: string | null;
  schedule: string | null;
  facebook: string | null;
  instagram: string | null;
  twitter: string | null;
  approved: boolean;
  status: "pending" | "approved" | "rejected" | "suspended";
  logo: string | null;
  imageUrl: string | null;
  adoptionFee: number | null;
  createdAt: Date;
  updatedAt: Date;
  acceptsDonations: boolean;
  donationCauseText: string | null;
  donationClabe: string | null;
  donationBankName: string | null;
  donationAccountHolder: string | null;
  donationPaypalLink: string | null;
  donationMercadoPagoLink: string | null;
  mapIframe: string | null;
};

export type UpdateShelterApiResponse = {
  shelter: {
    id: string;
    name: string;
    description: string | null;
    phone: string | null;
    email: string | null;
    website: string | null;
    municipality: string | null;
    fullAddress: string | null;
    schedule: string | null;
    facebook: string | null;
    instagram: string | null;
    twitter: string | null;
    approved: boolean;
    status: "pending" | "approved" | "rejected" | "suspended";
    logo: string | null;
    imageUrl: string | null;
    adoptionFee: number | null;
    createdAt: Date;
    updatedAt: Date;
    acceptsDonations: boolean;
    donationCauseText: string | null;
    donationClabe: string | null;
    donationBankName: string | null;
    donationAccountHolder: string | null;
    donationPaypalLink: string | null;
    donationMercadoPagoLink: string | null;
    mapIframe: string | null;
  };
  uploadUrls?: string[];
};
